apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f consul.yml
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  ports:
  - name: "8300"
    port: 8300
    targetPort: 8300
  - name: "8500"
    port: 8500
    targetPort: 8500
  - name: "8600"
    port: 8600
    targetPort: 8600
  selector:
    io.kompose.service: consul
status:
  loadBalancer: {}
