apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f consul.yml
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: consul-config-loader
  name: consul-config-loader
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consul-config-loader
    spec:
      containers:
      - env:
        - name: CONFIG_MODE
          value: git
        - name: CONSUL_PORT
          value: "8500"
        - name: CONSUL_URL
          value: consul
        - name: INIT_SLEEP_SECONDS
          value: "5"
        image: jhipster/consul-config-loader:v0.2.2
        name: consul-config-loader
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: consul-config-loader-claim0
      restartPolicy: Always
      volumes:
      - name: consul-config-loader-claim0
        persistentVolumeClaim:
          claimName: consul-config-loader-claim0
status: {}
