apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f consul.yml
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consul
    spec:
      containers:
      - args:
        - consul
        - agent
        - -dev
        - -ui
        - -client
        - 0.0.0.0
        image: consul:1.0.2
        name: consul
        ports:
        - containerPort: 8300
        - containerPort: 8500
        - containerPort: 8600
        resources: {}
      restartPolicy: Always
status: {}
