version: '2'
services:
    gateway-app:
        image: ccr.ccs.tencentyun.com/compose/gateway:1.0
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul.cmic.site
            - SPRING_CLOUD_CONSUL_PORT=8500
        ports:
            - 8080:8080

    uaa-app:
        image: ccr.ccs.tencentyun.com/compose/uaa:1.0
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul.cmic.site
            - SPRING_CLOUD_CONSUL_PORT=8500
        ports:
            - 9999:9999