version: '2'
services:
  uaa-app:
    image: uaa:1.0
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:mariadb://uaa-mariadb:13231/uaa
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  uaa-mariadb:
    extends:
      file: database.yml
      service: uaa-mariadb
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
